name: LateX to PDF

on:
  push:
    branches: 
      - master
      - main
    tags:
       - '*'
  pull_request:
    branches: [ master ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: latex2pdf
        id: compile-latex-document
        uses: thomas-chauvet/latex2pdf-action@1.1.0
        with:
          output_dir: output
          main_latex_file: test.tex
          ctan_packages: amsmath amsfonts lua-uni-algos
      - name: Upload PDF to the workflow tab
        id: upload-workflow-tab
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output/test.pdf
