name: LateX to PDF

on:
  push:
    branches:
      - master
      - main
    tags:
       - '*'
  pull_request:
    branches: [ master ]

  
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile test LaTeX document with Maths
        id: compile-latex-document-with-maths
        uses: ./
        with:
          output_dir: output
          main_latex_file: resources/test.tex
          ctan_packages: amsmath amsfonts lua-uni-algos
      - name: Upload PDF to the workflow tab
        id: upload-workflow-tab-maths
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output/test.pdf
      
      - name: Compile LaTeX document with fontawesome
        id: compile-latex-document-with-fontawesome
        uses: ./
        with:
          output_dir: output
          main_latex_file: root.tex
          ctan_packages: moderncv colortbl fontawesome lua-uni-algos
      - name: Upload PDF to the workflow tab
        id: upload-workflow-tab-fontawesome
        uses: actions/upload-artifact@v2
        with:
          name: output-fontawesome
          path: output/test-fontawesome.pdf

      - name: Compile LaTeX document with TOC
        id: compile-latex-document-with-toc
        uses: ./
        with:
          output_dir: output
          main_latex_file: resources/test-toc.tex
          ctan_packages: lua-uni-algos
          toc: true
      - name: Upload PDF to the workflow tab
        id: upload-workflow-tab-toc
        uses: actions/upload-artifact@v2
        with:
          name: output-toc
          path: output/test-toc.pdf
